# Generated by Django 6.1.1 on 2026-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='primary_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
